# Generated by Django 2.1.4 on 2018-12-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20181220_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='cpu_core_num',
        ),
        migrations.AlterField(
            model_name='host',
            name='host_status',
            field=models.CharField(choices=[('free', '空闲'), ('stoppage', '故障'), ('inuse', '使用中')], default='free', max_length=60, verbose_name='主机状态'),
        ),
    ]
