# Generated by Django 2.1.4 on 2018-12-28 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20181220_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='机柜位置')),
                ('desc', models.TextField(blank=True, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=255, unique=True, verbose_name='机房标识')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='机房名称')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='机房地址')),
                ('tel', models.CharField(blank=True, max_length=30, verbose_name='机房电话')),
                ('manager', models.CharField(blank=True, max_length=30, verbose_name='机房管理员')),
                ('mobile_phone', models.CharField(blank=True, max_length=30, verbose_name='移动电话')),
                ('cabinet_info', models.CharField(blank=True, max_length=30, verbose_name='机柜信息')),
                ('ip_range', models.CharField(blank=True, max_length=30, verbose_name='IP范围')),
                ('bandwidth', models.CharField(blank=True, max_length=30, verbose_name='接入带宽')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Cabinet', verbose_name='所属机柜'),
        ),
        migrations.AlterField(
            model_name='host',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Datacenter', verbose_name='所属数据中心'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Datacenter', verbose_name='所在机房'),
        ),
    ]
