# Generated by Django 2.1.4 on 2018-12-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20181228_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='desc',
        ),
    ]
