# Generated by Django 2.1.4 on 2018-12-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_remove_cabinet_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='desc',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
    ]
