# Generated by Django 2.1.4 on 2018-12-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_cabinet_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='host',
            name='datacenter',
        ),
    ]
