# Generated by Django 2.1.4 on 2018-12-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20181228_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Cabinet', verbose_name='所属机柜'),
        ),
        migrations.AddField(
            model_name='host',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Datacenter', verbose_name='所属数据中心'),
        ),
    ]
