# Generated by Django 2.1.4 on 2018-12-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20181228_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='datacenter',
        ),
    ]
