# Generated by Django 2.1.4 on 2018-12-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_remove_cabinet_datacenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Datacenter', verbose_name='所在机房'),
        ),
    ]
