# Generated by Django 2.1.4 on 2018-12-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_cabinet_datacenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='is_virtual',
        ),
        migrations.AlterField(
            model_name='host',
            name='host_status',
            field=models.CharField(blank=True, choices=[('free', '空闲'), ('stoppage', '故障'), ('inuse', '使用中')], default='free', max_length=60, null=True, verbose_name='主机状态'),
        ),
    ]
