# Generated by Django 2.1.4 on 2018-12-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0012_auto_20181228_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_type',
            field=models.CharField(blank=True, choices=[('phy', '物理机'), ('vir', '虚拟机'), ('container', '容器'), ('net', '网络设备'), ('safe', '安全设备'), ('other', '其他')], max_length=60, verbose_name='主机类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_status',
            field=models.CharField(choices=[('free', '空闲'), ('stoppage', '故障'), ('inuse', '使用中')], default='free', max_length=60, verbose_name='主机状态'),
        ),
    ]
