# Generated by Django 2.1.4 on 2018-12-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0014_host_other_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='os_version',
        ),
        migrations.RemoveField(
            model_name='host',
            name='outer_mac_addr',
        ),
        migrations.AlterField(
            model_name='host',
            name='created_time',
            field=models.DateTimeField(blank=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_innerip',
            field=models.GenericIPAddressField(verbose_name='管理IP地址'),
        ),
    ]
