# Generated by Django 2.1.4 on 2019-01-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0015_auto_20181230_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='created_time',
            field=models.DateTimeField(blank=True, verbose_name='上架时间'),
        ),
    ]
