# Generated by Django 2.1.4 on 2019-01-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0016_auto_20190101_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_status',
            field=models.CharField(choices=[('free', '空闲'), ('stoppage', '故障'), ('inuse', '使用中')], max_length=60, verbose_name='主机状态'),
        ),
    ]
