# Generated by Django 2.1.4 on 2019-01-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0017_auto_20190103_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_status',
            field=models.CharField(blank=True, choices=[('free', '空闲'), ('stoppage', '故障'), ('inuse', '使用中')], max_length=60, verbose_name='主机状态'),
        ),
        migrations.AlterField(
            model_name='host',
            name='mac_addr',
            field=models.CharField(blank=True, max_length=60, verbose_name='管理网MAC地址'),
        ),
        migrations.AlterField(
            model_name='host',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上次修改时间'),
        ),
    ]
