# Generated by Django 2.1.4 on 2019-01-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0018_auto_20190103_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu_core_count',
            field=models.CharField(blank=True, max_length=100, verbose_name='cpu逻辑核心数'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_num',
            field=models.CharField(blank=True, max_length=100, verbose_name='cpu个数'),
        ),
        migrations.AlterField(
            model_name='host',
            name='service_term',
            field=models.CharField(blank=True, max_length=100, verbose_name='质保年限'),
        ),
    ]
