# Generated by Django 2.1.4 on 2019-01-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0019_auto_20190103_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上架时间'),
        ),
    ]
