# Generated by Django 2.1.4 on 2019-01-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0020_auto_20190103_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_innerip',
            field=models.GenericIPAddressField(unique=True, verbose_name='管理IP地址'),
        ),
    ]
