# Generated by Django 2.1.4 on 2019-01-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0021_auto_20190103_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='fqdn_name',
        ),
        migrations.AlterField(
            model_name='host',
            name='host_name',
            field=models.CharField(max_length=100, verbose_name='主机名或fqdn名'),
        ),
    ]
