# Generated by Django 2.1.4 on 2019-01-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0022_auto_20190103_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu_core_count',
            field=models.CharField(blank=True, max_length=100, verbose_name='CPU逻辑核心数'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_module',
            field=models.CharField(blank=True, max_length=100, verbose_name='CPU型号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_num',
            field=models.CharField(blank=True, max_length=100, verbose_name='CPU个数'),
        ),
    ]
