# Generated by Django 2.1.4 on 2019-01-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0025_auto_20190115_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='service_term',
            field=models.IntegerField(blank=True, max_length=100, verbose_name='质保年限'),
        ),
    ]
