# Generated by Django 2.1.4 on 2019-01-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0027_auto_20190115_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='service_term',
            field=models.IntegerField(blank=True, null=True, verbose_name='质保年限'),
        ),
    ]
